FORMAT: 1A

# container-service-api

RESTful JSON API-blueprint for registering and modifying all types of containers for holding all types of material (sample, library etc...).
It can create, read and update a container (labware) and also add additional metadata to it.

## Labware Type Collection [/labware_types{?page%5Bnumber%5D,page%5Bsize%5D}]

### List All Labware Types [GET]

+ Parameters
   + page%5Bnumber%5D (number, optional) - Which page of material batches to return
   + page%5Bsize%5D (number, optional) - Number of material batches per page (default=10)

+ Response 200 (application/json)

        {
            "data": [
                {
                    "attributes": {
                        "name": "generic tube"
                    },
                    "id": "1",
                    "relationships": {
                        "layout": {
                            "data": {
                                "id": "1",
                                "type": "layouts"
                            }
                        }
                    },
                    "type": "labware-types"
                }
            ],
            "included": [
                {
                    "attributes": {
                        "name": "tube"
                    },
                    "id": "1",
                    "relationships": {
                        "locations": {
                            "data": [
                                {
                                    "id": "1",
                                    "type": "locations"
                                }
                            ]
                        }
                    },
                    "type": "layouts"
                }
            ]
        }

## Labware Type [/labware_types/{labware_id}{?page%5Bnumber%5D,page%5Bsize%5D}]
        
### Get a Labware Type [GET]

This action response with the queried labware type data.

+ Response 200 (application/json)

        {
          "data": {
            "id": "1",
            "type": "labware-types",
            "attributes": {
              "name": "generic tube"
            },
            "relationships": {
              "layout": {
                "data": {
                  "id": "1",
                  "type": "layouts"
                }
              }
            }
          },
          "included": [
            {
              "id": "1",
              "type": "layouts",
              "attributes": {
                "name": "tube"
              },
              "relationships": {
                "locations": {
                  "data": [
                    {
                      "id": "1",
                      "type": "locations"
                    }
                  ]
                }
              }
            }
          ]
        }

## Layout Collection [/layouts{?page%5Bnumber%5D,page%5Bsize%5D}]

### List All Layouts [GET]

+ Parameters
   + page%5Bnumber%5D (number, optional) - Which page of material batches to return
   + page%5Bsize%5D (number, optional) - Number of material batches per page (default=10)

+ Response 200 (application/json)

        {
            "data": [
                {
                    "attributes": {
                        "name": "tube"
                    },
                    "id": "1",
                    "relationships": {
                        "locations": {
                            "data": [
                                {
                                    "id": "1",
                                    "type": "locations"
                                }
                            ]
                        }
                    },
                    "type": "layouts"
                }
            ],
            "included": [
                {
                    "attributes": {
                        "name": "A1"
                    },
                    "id": "1",
                    "relationships": {
                        "layout": {
                            "data": {
                                "id": "1",
                                "type": "layouts"
                            }
                        }
                    },
                    "type": "locations"
                }
            ]
        }
        
## Layout [/layouts/{layout_id}]
        
### Get a Layout [GET]

This action response with the queried layout data.

+ Response 200 (application/json)

        {
          "data": {
            "id": "1",
            "type": "layouts",
            "attributes": {
              "name": "tube"
            },
            "relationships": {
              "locations": {
                "data": [
                  {
                    "id": "1",
                    "type": "locations"
                  }
                ]
              }
            }
          },
          "included": [
            {
              "id": "1",
              "type": "locations",
              "attributes": {
                "name": "A1"
              },
              "relationships": {
                "layout": {
                  "data": {
                    "id": "1",
                    "type": "layouts"
                  }
                }
              }
            }
          ]
        }

## Labware Collection [/labwares{?page%5Bnumber%5D,page%5Bsize%5D,labware_type,barcode,barcode_prefix,barcode_info,external_id,created_after,created_before}]

### List All Labwares [GET]

+ Parameters
   + page%5Bnumber%5D (number, optional) - Which page of material batches to return
   + page%5Bsize%5D (number, optional) - Number of material batches per page (default=10)
   + labware_type (string, optional) - Only show labware of this type
   + barcode (string, optional) - Only show labware with this exact barcode
   + barcode_prefix (string, optional) - Only show labware a barcode starting with this
   + barcode_info (string, optional) - Only show labware a barcode containing this
   + external_id (string, optional) - Only show labware with this external id
   + created_after (dateTime, optional) - Only show labware made after this time
   + created_before (dateTime, optional) - Only show labware made before this time

+ Response 200 (application/json)

        {
          "data": [
            {
              "id": "da514d60-f5cc-0133-e4e4-2cbc32c89153",
              "type": "labwares",
              "attributes": {
                "external-id": null,
                "barcode": "TEST_1"
              },
              "relationships": {
                "labware-type": {
                  "data": {
                    "id": "1",
                    "type": "labware-types"
                  }
                },
                "receptacles": {
                  "data": [
                    {
                      "id": "1",
                      "type": "receptacles"
                    },
                    {
                      "id": "2",
                      "type": "receptacles"
                    }
                  ]
                },
                "metadata": {
                  "data": [
                    {
                      "id": "1",
                      "type": "metadata"
                    },
                    {
                      "id": "2",
                      "type": "metadata"
                    },
                    {
                      "id": "3",
                      "type": "metadata"
                    }
                  ]
                }
              }
            }
          ],
          "included": [
            {
              "id": "1",
              "type": "labware-types",
              "attributes": {
                "name": "test_plate_96"
              },
              "relationships": {
                "layout": {
                  "data": {
                    "id": "1",
                    "type": "layouts"
                  }
                }
              }
            },
            {
              "id": "1",
              "type": "receptacles",
              "attributes": {
                "material-uuid": null
              },
              "relationships": {
                "location": {
                  "data": {
                    "id": "1",
                    "type": "locations"
                  }
                }
              }
            },
            {
              "id": "1",
              "type": "locations",
              "attributes": {
                "name": "A1"
              },
              "relationships": {
                "layout": {
                  "data": {
                    "id": "1",
                    "type": "layouts"
                  }
                }
              }
            },
            {
              "id": "2",
              "type": "receptacles",
              "attributes": {
                "material-uuid": null
              },
              "relationships": {
                "location": {
                  "data": {
                    "id": "2",
                    "type": "locations"
                  }
                }
              }
            },
            {
              "id": "2",
              "type": "locations",
              "attributes": {
                "name": "A2"
              },
              "relationships": {
                "layout": {
                  "data": {
                    "id": "1",
                    "type": "layouts"
                  }
                }
              }
            },
            {
              "id": "1",
              "type": "metadata",
              "attributes": {
                "key": "test_key_1",
                "value": "test_value_1"
              }
            },
            {
              "id": "2",
              "type": "metadata",
              "attributes": {
                "key": "test_key_2",
                "value": "test_value_2"
              }
            },
            {
              "id": "3",
              "type": "metadata",
              "attributes": {
                "key": "test_key_3",
                "value": "test_value_3"
              }
            }
          ]
        }

## Labware [/labwares/{labware_uuid}]
        
### Get a Labware [GET]

This action response with the queried labware data.

+ Response 200 (application/json)

        {
          "data": {
            "id": "5e871ae0-f5cd-0133-e4e5-2cbc32c89153",
            "type": "labwares",
            "attributes": {
              "external-id": null,
              "barcode": "TEST_1"
            },
            "relationships": {
              "labware-type": {
                "data": {
                  "id": "1",
                  "type": "labware-types"
                }
              },
              "metadata": {
                "data": [
                  {
                    "id": "63",
                    "type": "metadata"
                  },
                  {
                    "id": "64",
                    "type": "metadata"
                  },
                  {
                    "id": "65",
                    "type": "metadata"
                  }
                ]
              },
              "receptacles": {
                "data": [
                  {
                    "id": "1",
                    "type": "receptacles"
                  },
                  {
                    "id": "2",
                    "type": "receptacles"
                  }
                ]
              },
              "metadata": {
                "data": [
                  {
                    "id": "1",
                    "type": "metadata"
                  },
                  {
                    "id": "2",
                    "type": "metadata"
                  },
                  {
                    "id": "3",
                    "type": "metadata"
                  }
                ]
              }
            }
          },
          "included": [
            {
              "id": "1",
              "type": "labware-types",
              "attributes": {
                "name": "test_plate_2"
              },
              "relationships": {
                "layout": {
                  "data": {
                    "id": "1",
                    "type": "layouts"
                  }
                }
              }
            },
            {
              "id": "1",
              "type": "receptacles",
              "attributes": {
                "material-uuid": null
              },
              "relationships": {
                "location": {
                  "data": {
                    "id": "1",
                    "type": "locations"
                  }
                }
              }
            },
            {
              "id": "1",
              "type": "locations",
              "attributes": {
                "name": "A1"
              },
              "relationships": {
                "layout": {
                  "data": {
                    "id": "1",
                    "type": "layouts"
                  }
                }
              }
            },
            {
              "id": "2",
              "type": "receptacles",
              "attributes": {
                "material-uuid": null
              },
              "relationships": {
                "location": {
                  "data": {
                    "id": "2",
                    "type": "locations"
                  }
                }
              }
            },
            {
              "id": "2",
              "type": "locations",
              "attributes": {
                "name": "A2"
              },
              "relationships": {
                "layout": {
                  "data": {
                    "id": "1",
                    "type": "layouts"
                  }
                }
              }
            },
            {
              "id": "1",
              "type": "metadata",
              "attributes": {
                "key": "test_key_1",
                "value": "test_value_1"
              }
            },
            {
              "id": "2",
              "type": "metadata",
              "attributes": {
                "key": "test_key_2",
                "value": "test_value_2"
              }
            },
            {
              "id": "3",
              "type": "metadata",
              "attributes": {
                "key": "test_key_3",
                "value": "test_value_3"
              }
            },
            {
              "id": "63",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 1",
                "value": "metadatum value 1"
              }
            },
            {
              "id": "64",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 2",
                "value": "metadatum value 2"
              }
            },
            {
              "id": "65",
              "type": "metadata",
              "attributes": {
                "key": "metadatum key 3",
                "value": "metadatum value 3"
              }
            }
          ]
        }

## Labware creation [/labwares/]

You can create a new Labware using this action. It takes a JSON-API compatible
object containing data of the new Labware. It is mandatory to has a Labware Type relationship.
It is optional to the labware to has one or more metadata relationship(s).

### Create a new empty Labware without attached metadata [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "barcode_info": "XYZ",
                    "barcode_prefix": "TEST",
                    "external_id": "TICKET_5"
                },
                "relationships": {
                    "labware_type": {
                        "data": {
                            "attributes": {
                                "name": "test_plate_2"
                            }
                        }
                    }
                }
            }
        }
        
+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /labwares/77ad1f30-f7f3-0133-e4e7-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_3",
                        "external-id": "TICKET_5"
                    },
                    "id": "77ad1f30-f7f3-0133-e4e7-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": []
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "5",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "6",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": null
                        },
                        "id": "5",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": null
                        },
                        "id": "6",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    }
                ]
            }

### Create a new empty Labware with a given barcode [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "barcode": "TEST_BARCODE",
                    "external_id": "TICKET_7"
                },
                "relationships": {
                    "labware_type": {
                        "data": {
                            "attributes": {
                                "name": "test_plate_2"
                            }
                        }
                    }
                }
            }
        }
        
+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /labwares/cda330d0-f7f3-0133-e4e8-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_BARCODE",
                        "external-id": "TICKET_7"
                    },
                    "id": "cda330d0-f7f3-0133-e4e8-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": []
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "7",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "8",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": null
                        },
                        "id": "7",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": null
                        },
                        "id": "8",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    }
                ]
            }

+ Response 422 (application/json)

        {
            "barcode": "has already been taken"
        }

### Create a new empty Labware with a given UUID [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "barcode_prefix": "TEST",
                    "external_id": "TICKET_10"
                },
                "id": "42896cc0-f403-0133-c07c-2cbc32c89153",
                "relationships": {
                    "labware_type": {
                        "data": {
                            "attributes": {
                                "name": "test_plate_2"
                            }
                        }
                    }
                }
            }
        }
        
+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /labwares/42896cc0-f403-0133-c07c-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_5",
                        "external-id": "TICKET_10"
                    },
                    "id": "42896cc0-f403-0133-c07c-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": []
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "9",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "10",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": null
                        },
                        "id": "9",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": null
                        },
                        "id": "10",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    }
                ]
            }

+ Response 422 (application/json)

        {
            "uuid": "has already been taken"
        }

+ Response 422 (application/json)

        {
            "uuid": "is not a valid UUID"
        }

### Create a new Labware with metadata [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "barcode_info": "XYZ",
                    "barcode_prefix": "TEST",
                    "external_id": "TICKET_34"
                },
                "relationships": {
                    "labware_type": {
                        "data": {
                            "attributes": {
                                "name": "test_plate_2"
                            }
                        }
                    },
                    "metadata": {
                        "data": [
                            {
                                "attributes": {
                                    "key": "metadatum key 13",
                                    "value": "metadatum value 13"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "metadatum key 14",
                                    "value": "metadatum value 14"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "metadatum key 15",
                                    "value": "metadatum value 15"
                                }
                            }
                        ]
                    }
                }
            }
        }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /labwares/89b8ebb0-f7f6-0133-e4e9-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_6_changed",
                        "external-id": "TICKET_34"
                    },
                    "id": "89b8ebb0-f7f6-0133-e4e9-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": [
                                {
                                    "id": "4",
                                    "type": "metadata"
                                },
                                {
                                    "id": "5",
                                    "type": "metadata"
                                },
                                {
                                    "id": "6",
                                    "type": "metadata"
                                }
                            ]
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "11",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "12",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": "ab9eb230-f408-0133-c33b-2cbc32c89153"
                        },
                        "id": "11",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979f980-f404-0133-c10b-2cbc32c89153"
                        },
                        "id": "12",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 13",
                            "value": "metadatum value 13"
                        },
                        "id": "4",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 14",
                            "value": "metadatum value 14"
                        },
                        "id": "5",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 15",
                            "value": "metadatum value 15"
                        },
                        "id": "6",
                        "type": "metadata"
                    }
                ]
            }

### Create a new Labware with materials [POST]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "barcode_info": "XYZ",
                    "barcode_prefix": "TEST",
                    "external_id": "TICKET_16"
                },
                "relationships": {
                    "labware_type": {
                        "data": {
                            "attributes": {
                                "name": "test_plate_2"
                            }
                        }
                    },
                    "receptacles": {
                        "data": [
                            {
                                "attributes": {
                                    "material_uuid": "2979aa40-f404-0133-c10a-2cbc32c89153"
                                },
                                "relationships": {
                                    "location": {
                                        "data": {
                                            "attributes": {
                                                "name": "A1"
                                            }
                                        }
                                    }
                                }
                            },
                            {
                                "attributes": {
                                    "material_uuid": "2979f980-f404-0133-c10b-2cbc32c89153"
                                },
                                "relationships": {
                                    "location": {
                                        "data": {
                                            "attributes": {
                                                "name": "A2"
                                            }
                                        }
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        }
        
+ Response 201 (application/vnd.api+json)

    + Headers

            Location: /labwares/89b8ebb0-f7f6-0133-e4e9-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_6",
                        "external-id": "TICKET_16"
                    },
                    "id": "89b8ebb0-f7f6-0133-e4e9-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": []
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "11",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "12",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979aa40-f404-0133-c10a-2cbc32c89153"
                        },
                        "id": "11",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979f980-f404-0133-c10b-2cbc32c89153"
                        },
                        "id": "12",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    }
                ]
            }

## Labware update [/labwares/{labware_uuid} PUT]

### Update an existing Labware with a barcode and external ticket ID [PUT]

+ Request (application/vnd.api+json)

        {
            "data": {
                "attributes": {
                    "barcode": "TEST_XYZ_6_changed",
                    "external_id": "TICKET_16_changed"
                }
            }
        }

+ Response 200 (application/vnd.api+json)

    + Headers

            Location: /materials/89b8ebb0-f7f6-0133-e4e9-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_6_changed",
                        "external-id": "TICKET_16_changed"
                    },
                    "id": "89b8ebb0-f7f6-0133-e4e9-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": []
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "11",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "12",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979aa40-f404-0133-c10a-2cbc32c89153"
                        },
                        "id": "11",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979f980-f404-0133-c10b-2cbc32c89153"
                        },
                        "id": "12",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    }
                ]
            }

+ Response 422 (application/json)

        {
            "barcode": "has already been taken"
        }

### Update an existing Labware: add a material to a receptacle [PUT]

+ Request (application/vnd.api+json)

        {
            "data": {
                "relationships": {
                    "receptacles": {
                        "data": [
                            {
                                "attributes": {
                                    "material_uuid": "eccd60d0-f401-0133-bfbf-2cbc32c89153"
                                },
                                "relationships": {
                                    "location": {
                                        "data": {
                                            "attributes": {
                                                "name": "A1"
                                            }
                                        }
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        }

+ Response 200 (application/vnd.api+json)

    + Headers

            Location: /labwares/89b8ebb0-f7f6-0133-e4e9-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_6_changed",
                        "external-id": "TICKET_16_changed"
                    },
                    "id": "89b8ebb0-f7f6-0133-e4e9-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": []
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "11",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "12",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": "eccd60d0-f401-0133-bfbf-2cbc32c89153"
                        },
                        "id": "11",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": null
                        },
                        "id": "12",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    }
                ]
            }

+ Response 422 (application/json)

        {
            "location": "is not a valid location"
        }

### Update an existing Labware: change a material in a receptacle [PUT]

+ Request (application/vnd.api+json)

        {
            "data": {
                "relationships": {
                    "receptacles": {
                        "data": [
                            {
                                "attributes": {
                                    "material_uuid": "ab9eb230-f408-0133-c33b-2cbc32c89153"
                                },
                                "relationships": {
                                    "location": {
                                        "data": {
                                            "attributes": {
                                                "name": "A1"
                                            }
                                        }
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        }

+ Response 200 (application/vnd.api+json)

    + Headers

            Location: /labwares/89b8ebb0-f7f6-0133-e4e9-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_6_changed",
                        "external-id": "TICKET_16_changed"
                    },
                    "id": "89b8ebb0-f7f6-0133-e4e9-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": []
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "11",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "12",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": "ab9eb230-f408-0133-c33b-2cbc32c89153"
                        },
                        "id": "11",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979f980-f404-0133-c10b-2cbc32c89153"
                        },
                        "id": "12",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    }
                ]
            }

+ Response 422 (application/json)

        {
            "location": "is not a valid location"
        }

### Update the existing metadata [PUT]

+ Request (application/vnd.api+json)

        {
            "data": {
                "relationships": {
                    "metadata": {
                        "data": [
                            {
                                "attributes": {
                                    "key": "metadatum key 13",
                                    "value": "metadatum value 13_changed"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "metadatum key 14",
                                    "value": "metadatum value 14_changed"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "metadatum key 15",
                                    "value": "metadatum value 15_changed"
                                }
                            }
                        ]
                    }
                }
            }
        }


+ Response 200 (application/vnd.api+json)

    + Headers

            Location: /labwares/89b8ebb0-f7f6-0133-e4e9-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_6_changed",
                        "external-id": "TICKET_34"
                    },
                    "id": "89b8ebb0-f7f6-0133-e4e9-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": [
                                {
                                    "id": "4",
                                    "type": "metadata"
                                },
                                {
                                    "id": "5",
                                    "type": "metadata"
                                },
                                {
                                    "id": "6",
                                    "type": "metadata"
                                }
                            ]
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "11",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "12",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": "ab9eb230-f408-0133-c33b-2cbc32c89153"
                        },
                        "id": "11",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979f980-f404-0133-c10b-2cbc32c89153"
                        },
                        "id": "12",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 13",
                            "value": "metadatum value 13_changed"
                        },
                        "id": "4",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 14",
                            "value": "metadatum value 14_changed"
                        },
                        "id": "5",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 15",
                            "value": "metadatum value 15_changed"
                        },
                        "id": "6",
                        "type": "metadata"
                    }
                ]
            }

### Update labware with additional metadata [PUT]

+ Request (application/vnd.api+json)

        {
            "data": {
                "relationships": {
                    "metadata": {
                        "data": [
                            {
                                "attributes": {
                                    "key": "metadatum key 25",
                                    "value": "metadatum value 25"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "metadatum key 26",
                                    "value": "metadatum value 26"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "metadatum key 27",
                                    "value": "metadatum value 27"
                                }
                            },
                            {
                                "attributes": {
                                    "key": "metadatum key 28",
                                    "value": "metadatum value 28"
                                }
                            }
                        ]
                    }
                }
            }
        }


+ Response 200 (application/vnd.api+json)

    + Headers

            Location: /labwares/89b8ebb0-f7f6-0133-e4e9-2cbc32c89153

    + Body

            {
                "data": {
                    "attributes": {
                        "barcode": "TEST_XYZ_6_changed",
                        "external-id": "TICKET_34"
                    },
                    "id": "89b8ebb0-f7f6-0133-e4e9-2cbc32c89153",
                    "relationships": {
                        "labware-type": {
                            "data": {
                                "id": "1",
                                "type": "labware-types"
                            }
                        },
                        "metadata": {
                            "data": [
                                {
                                    "id": "4",
                                    "type": "metadata"
                                },
                                {
                                    "id": "5",
                                    "type": "metadata"
                                },
                                {
                                    "id": "6",
                                    "type": "metadata"
                                },
                                {
                                    "id": "7",
                                    "type": "metadata"
                                },
                                {
                                    "id": "8",
                                    "type": "metadata"
                                },
                                {
                                    "id": "9",
                                    "type": "metadata"
                                },
                                {
                                    "id": "10",
                                    "type": "metadata"
                                }
                            ]
                        },
                        "receptacles": {
                            "data": [
                                {
                                    "id": "11",
                                    "type": "receptacles"
                                },
                                {
                                    "id": "12",
                                    "type": "receptacles"
                                }
                            ]
                        }
                    },
                    "type": "labwares"
                },
                "included": [
                    {
                        "attributes": {
                            "name": "test_plate_2"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "labware-types"
                    },
                    {
                        "attributes": {
                            "material-uuid": "ab9eb230-f408-0133-c33b-2cbc32c89153"
                        },
                        "id": "11",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "1",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A1"
                        },
                        "id": "1",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "material-uuid": "2979f980-f404-0133-c10b-2cbc32c89153"
                        },
                        "id": "12",
                        "relationships": {
                            "location": {
                                "data": {
                                    "id": "2",
                                    "type": "locations"
                                }
                            }
                        },
                        "type": "receptacles"
                    },
                    {
                        "attributes": {
                            "name": "A2"
                        },
                        "id": "2",
                        "relationships": {
                            "layout": {
                                "data": {
                                    "id": "1",
                                    "type": "layouts"
                                }
                            }
                        },
                        "type": "locations"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 13",
                            "value": "metadatum value 13_changed"
                        },
                        "id": "4",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 14",
                            "value": "metadatum value 14_changed"
                        },
                        "id": "5",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 15",
                            "value": "metadatum value 15_changed"
                        },
                        "id": "6",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 25",
                            "value": "metadatum value 25"
                        },
                        "id": "7",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 26",
                            "value": "metadatum value 26"
                        },
                        "id": "8",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 27",
                            "value": "metadatum value 27"
                        },
                        "id": "9",
                        "type": "metadata"
                    },
                    {
                        "attributes": {
                            "key": "metadatum key 28",
                            "value": "metadatum value 28"
                        },
                        "id": "10",
                        "type": "metadata"
                    }
                ]
            }